### ISSUE TITLE
Docker-compose fails

### ISSUE THREAD

**Issue by tungnnt** [maulidihsan/sawtooth-analitica#13]
Hello support team,
I am a newbie here. I run ```docker-compose up``` but got the error: ```The container name "/analitica-tp" is already in use```
Please help me

**Comment by maulidihsan** [comment]
Hi @tungnnt, can you test with the new docker-compose.yml? I think it's related to container_name config so I commented it. I think it's because we use 3 replicas for transaction processors, docker need to have unique name for each replicas.
